bringg-prod-status-master/bringg-prod-status-master/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'status#index'

  get 'status/create' => 'status#create'
  post 'status/create' => 'status#create'

  resources :status, :only => [:index, :update, :create] do

  end
end

bringg-prod-status-master/bringg-prod-status-master/app/models/status.rb
class Status < ActiveRecord::Base

  belongs_to :user, foreign_key: "created_by_user"

  ORIGINS = {
      rails: 0,
      node: 1,
      dashboard: 2,
      devops: 3,
      mobile: 4,
      other: 5
  }

  ORIGIN_LABELS = ['RAILS', 'NODE', 'DASHBOARD', 'DEVOPS', 'MOBILE', 'OTHER']

  def get_origin_label
    return ORIGIN_LABELS[self.incident_origin]
  end
end

bringg-prod-status-master/bringg-prod-status-master/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

bringg-prod-status-master/bringg-prod-status-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

bringg-prod-status-master/bringg-prod-status-master/app/controllers/status_controller.rb
class StatusController < ApplicationController
  def index
    @status = Status.last
    @last_ten = Status.last(10)
  end

  def create


    if params[:incident_date]
      params.require(:incident_description)
      params.require(:incident_date)
      params.require(:incident_origin)
      params[:incident_date] = DateTime.new(params[:incident_date]["(1i)"].to_i,
                                            params[:incident_date]["(2i)"].to_i,
                                            params[:incident_date]["(3i)"].to_i,
                                            params[:incident_date]["(4i)"].to_i,
                                            params[:incident_date]["(5i)"].to_i)
      params[:created_by_user] = current_user.id
      @status = Status.create(create_status_params)
      redirect_to action: "index"
    else
      render 'create'
    end
  end

  private

  def create_status_params
    params.permit(:incident_description, :incident_date, :incident_origin, :created_by_user)
  end
end

bringg-prod-status-master/bringg-prod-status-master/app/helpers/application_helper.rb
module ApplicationHelper
end

bringg-prod-status-master/bringg-prod-status-master/app/helpers/status_helper.rb
module StatusHelper
end

bringg-prod-status-master/bringg-prod-status-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BringgProdStatus</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= google_webfonts_init({google: ['Open+Sans']}) %>

  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

bringg-prod-status-master/bringg-prod-status-master/app/views/status/create.html.erb
<div class="create-new-status-wrapper">
  <div class="create-new-status">
    <div class="header">Create new status</div>


    <%= form_tag "/status/create" do %>
        <div class="field-set"><label>Incident Description</label><%= text_area_tag "incident_description", nil, rows: 10, cols: 25 %></div>
        <div class="field-set"><label>Incident Date</label><%= datetime_select  "incident_date", nil %></div>
        <div class="field-set"><label>Incident Origin</label><%= select(nil, "incident_origin", Status::ORIGINS, {:include_blank => true}) %></div>
        <%= submit_tag "Save" %>
    <% end %>

    <button type="button" class="button"><%= link_to 'Back', root_path %></button>

  </div>
</div>

bringg-prod-status-master/bringg-prod-status-master/app/views/status/index.html.erb
<div>
  <h2>Last Production Issue Incident Was</h2>

  <div class="flip-counter clock flip-clock-wrapper"></div>
  <div class="incident-description-wrapper">
    <div class="inner-wrapper">
      <div class="panel">
        <h3>Incident Description</h3>
        <span class="description"><%= @status.incident_description %></span>
        <span class="date">Date: <%= @status.incident_date.to_formatted_s(:short) %></span>
        <span class="origin">Origin: <%= @status.get_origin_label %></span>
        <span class="created_by">Reporter: <%= @status.user.email %></span>
      </div>

      <div class="panel incidents-list">
        <h3>Last 10 Incidents</h3>
        <ul>
          <% @last_ten.each do |incident| %>
              <li class="incident-item">
                <div class="date"><%= incident.incident_date.to_formatted_s(:short) %></div>
                |
                <div class="description"><%= incident.incident_description %></div>
              </li>
          <% end %>
        </ul>
      </div>
    </div>

    <div class="footer">
      <button type="button" class="button"><%= link_to 'NEW INCIDENT', status_create_path %></button>
    </div>
  </div>

  <script>

      var clock;
      $(document).ready(function () {
          var currentDate = new Date();

          var pastDate = new Date(<%= @status.incident_date.to_i * 1000%>);

          var diff = currentDate.getTime() / 1000 - pastDate.getTime() / 1000;
          var diffInDays = currentDate.getTime() / 24 - pastDate.getTime() / 24;

          clock = $('.clock').FlipClock(diff, {
              clockFace: 'DailyCounter'
          });


          var a = moment(currentDate);
          var b = moment(pastDate);
          var diffDays = Math.abs(b.diff(a, 'days'));
          var backgroundBodyColors = ['D0021B', 'F5A623', '417505', '4A90E2', '1F1F1F'];
          var colorPos = diffDays > backgroundBodyColors.length ? backgroundBodyColors.length : diffDays;
          $("body").css("background-color", '#' + backgroundBodyColors[colorPos]);
      });
  </script>
</div>